package com.bbng.dao.microservices.auth.auditlog;

public enum Events {
    LOGIN, SIGNUP, CHANGE_PASSWORD, RESET_PASSWORD, DEPOSIT, TRANSFER, VTU_BILL_TRANSACTION,
    ELECTRICITY_BILL_TRANSACTION, DATA_BILL_TRANSACTION, TV_BILL_TRANSACTION, ASSIGN_PERMISSION,
    INVITE_STAFF, ONBOARD_MERCHANT, ONBOARD_MERCHANT_ADMIN, SEND_NOTIFICATIONS, DELETE_NOTIFICATIONS, DISABLE_STAFF, DISABLE_PERMISSION, DECLINE_KYC, ACCEPT_KYC, APPROVE_KYC,
    ACCEPT_PAYMENT, DECLINE_PAYMENT, APPROVE_PAYMENT, BET_BILL_TRANSACTION, CREATED_TEST_KEY, CREATED_LIVE_KEY
}
